- name: Prerequisites
  hosts: localhost
  connection: local
  vars_files:
   - vars.yml

  tasks:

    - name: Create an Azure Container Registry for Azure Function
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
