- name: Prerequisites
  hosts: localhost
  connection: local
  vars_files:
   - ./vars-myvars.yml

  tasks:
    - name: Create Resource Group
      azure_rm_resourcegroup:
        name: "{{ resource_group }}"
        location: "{{ location }}"
