- name: Create a Docker container with function app
  hosts: localhost
  connection: local
  vars_files:
   - ./vars.yml

  tasks:
    - name: Build and push Docker image
      docker_image:
        build:
          path: ./helloworld
        name: zikalino/helloworld
        source: build
        push: yes
