- name: Build Docker Container for ARO lab
  hosts: localhost
  connection: local
  vars_files:
   - ./vars.yml

  tasks:
    - name: Log into DockerHub
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Build and push Docker image for ARO into Docker Hub
      docker_image:
        build:
          path: ./helloworld-aro
        name: "{{ docker_username }}/helloworld-aro1"
        source: build
        push: yes

