- name: Create a Docker container with function app
  hosts: localhost
  connection: local
  vars_files:
   - ./vars-myvars.yml

  tasks:
    - name: Log into DockerHub
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Build and push Docker image for AKS
      docker_image:
        build:
          path: ./helloworld
        name: "{{ docker_username }}/helloworld"
        source: build
        push: yes

    - name: Build and push Docker image for ARO
      docker_image:
        build:
          path: ./helloworld-aro
        name: "{{ docker_username }}/helloworld-aro1"
        source: build
        push: yes

