- name: Build Containers for AKS and ARO and push to Docker Hub
  hosts: localhost
  connection: local
  vars_files:
   - ./vars-myvars.yml

  tasks:
    - name: Log into Docker Hub
      docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"

    - name: Build and Push Docker Container for AKS Demo
      docker_image:
        build:
          path: ./helloworld
        name: "{{ docker_username }}/helloworld"
        source: build
        push: yes

    - name: Build and Push Docker Container for ARO Demo
      docker_image:
        build:
          path: ./helloworld-aro
        name: "{{ docker_username }}/helloworld-aro"
        source: build
        push: yes
