- name: Use Azure Container Registry to build a container image
  hosts: localhost
  connection: local
  vars_files:
   - ./vars-myvars.yml

  tasks:

    - name: Create a new Azure Container Registry
      azure_rm_containerregistry:
        name: "{{ acr_name }}"
        resource_group: "{{ resource_group }}"
        admin_user_enabled: true
        sku: Premium
        tags:
            Release: Initial
            Environment: Ansiblefest2019
           
    - name: Build container image using Azure Container Registry
      azure_rm_resource:
        api_version: '2019-06-01-preview'
        resource_group: "{{ resource_group }}"
        provider: ContainerRegistry
        resource_type: registries
        resource_name: "{{ acr_name }}"
        subresource:
          - type: tasks
            name: "buildtask"
        body:
          properties: 
            status: Enabled
            platform: 
              os: Linux
              architecture: amd64
            agentConfiguration: 
              cpu: 2
            step: 
              type: Docker
              imageNames: 
                - helloworld
              dockerFilePath: Dockerfile
              contextPath: helloworld
              isPushEnabled: true
              noCache: false
            trigger: 
              sourceTriggers: 
                - name: mySourceTrigger
                  sourceRepository: 
                    sourceControlType: Github
                    repositoryUrl: https://github.com/{{ github_id }}/Ansiblefest2019
                    branch: master
                    sourceControlAuthProperties: 
                      tokenType: PAT
                      token:  "{{ github_token }}"
                  sourceTriggerEvents: 
                    - commit
              baseImageTrigger: 
                name: myBaseImageTrigger
                baseImageTriggerType: Runtime
          location: "{{ location }}"

    - name: Schedule first run
      azure_rm_resource:
        api_version: '2019-06-01-preview'
        method: POST
        resource_group: "{{ resource_group }}"
        provider: ContainerRegistry
        resource_type: registries
        resource_name: "{{ acr_name }}"
        subresource:
          - type: scheduleRun
        body:
          type: TaskRunRequest
          taskId: "/subscriptions/{{ lookup('env', 'SUBSCRIPTION_ID') }}/resourceGroups/{{ resource_group }}/providers/Microsoft.ContainerRegistry/registries/{{ acr_name }}/tasks/buildtask"

