- name: Create a Docker container with function app
  hosts: localhost
  connection: local
  vars_files:
   - vars.yml

  tasks:
           
    - name: Schedule first run
      azure_rm_resource:
        api_version: '2019-06-01-preview'
        method: POST
        resource_group: "{{ resource_group }}"
        provider: ContainerRegistry
        resource_type: registries
        resource_name: "{{ acr_name }}"
        subresource:
          - type: scheduleRun
        body:
          type: TaskRunRequest
          taskId: "/subscriptions/{{ lookup('env', 'SUBSCRIPTION_ID') }}/resourceGroups/{{ resource_group }}/providers/Microsoft.ContainerRegistry/registries/{{ acr_name }}/tasks/buildtask"
