---
- hosts: localhost
  vars_files:
    - ./vars-myvars.yml
  tasks:
   
    - name: Randomize AKS resource names
      set_fact:
         dns_prefix: "aks{{ resource_group | hash('md5') | truncate(10, True, '') }}"
         aks_name: "aks{{ resource_group | hash('md5') | truncate(7, True, '') }}"

    - name: Create an AKS instance
      azure_rm_aks:
         name: "{{ aks_name }}"
         resource_group: "{{ resource_group }}"
         location: "{{ location }}"
         dns_prefix: "{{ dns_prefix }}"
         kubernetes_version: 1.12.7
         service_principal:
             client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
             client_secret: "{{ lookup('env', 'AZURE_SECRET') }}"
         linux_profile:
             admin_username:  "{{ admin_username }}"
             ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
         agent_pool_profiles:
             - name: default
               count: 1
               vm_size: Standard_DS1_v2
      register: aks

    - name: Verify .kube directory exists
      file: 
        path: "~/.kube"
        state: "directory"
        mode: "0755"

    - name: Save kubectl configuration file
      copy:
        content: "{{ aks.kube_config }}"
        dest: "~/.kube/config"
