- name: Deploy CosmosDB & K8S Infrastructure to support Hero Voting App
  hosts: localhost
  connection: local
  vars_files:
    - ./vars.yml
  roles:
    - ../modules

  tasks:

    - name: Create Cosmos DB (MongoDB) for Lab Exercises
      azure_rm_cosmosdbaccount:
        resource_group: "{{ resource_group }}"
        name: "ansiblefest-cosmosdb"
        kind: mongo_db
        state: present
        enable_aggregation_pipeline: true
        enable_multiple_write_locations: false
        consistency_policy:
          default_consistency_level: "consistent_prefix"
        geo_rep_locations:
          - name: "{{ location }}"
            failover_priority: 0
        database_account_offer_type: Standard

