---
- hosts: localhost
  vars_files:
    - ./vars-myvars.yml
  tasks:

    - name: Deploy an image to AKS
      k8s_raw:
          state: present
          force: true
          kubeconfig: "~/.kube/config"
          src: "aks-k8s-hero-voting-deploy.yml"
      register: output

    #- name: Expose to external
      #k8s_raw:
          #state: present
          #kubeconfig: "~/.kube/config"
          #src: "service.yml"
      #register: output

    - debug:
        var: output
