---
- hosts: localhost
  vars_files:
    - vars.yml
  tasks:

    - name: Deploy an image to AKS
      k8s_raw:
          state: present
          force: true
          kubeconfig: ".config"
          src: "deployment.yml"

    - name: Expose to external
      k8s_raw:
          state: present
          kubeconfig: ".config"
          src: "service.yml"
      register: output

    - debug:
          msg: "http://{{ output.result.status.loadBalancer.ingress[0].ip }}"
