---
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - ./modules 
  tasks:
    - name: Create/Update OpenShift Managed Cluster
      openshiftmanagedcluster:
        resource_group: "{{ resource_group }}"
        name: "{{ aro_cluster_name }}"
        location: eastus
        open_shift_version: v3.11
        network_profile:
          vnet_cidr: 10.0.0.0/8
        router_profiles:
          - name: default
        master_pool_profile:
          name: master
          count: 3
          vm_size: Standard_D4s_v3
          subnet_cidr: 10.0.0.0/24
          os_type: Linux
        agent_pool_profiles:
          - name: infra
            count: 2
            vm_size: Standard_D4s_v3
            subnet_cidr: 10.0.0.0/24
            os_type: Linux
            role: infra
          - name: compute
            count: 4
            vm_size: Standard_D4s_v3
            subnet_cidr: 10.0.0.0/24
            os_type: Linux
            role: compute
        auth_profile:
          identity_providers:
            - name: Azure AD
              provider:
                kind: AADIdentityProvider
                clientId: "{{ aro_client_id }}"
                secret: "{{ aro_secret }}"
                tenantId: "{{ aro_tenant_id }}"
      register: output

    - debug:
        msg: "https://{{ output.properties.publicHostname }}"
