 name: Deploy Azure Red Hat OpenShift Cluster
  hosts: localhost
  vars_files:
    - ./vars-myvars.yml
  roles:
    - ./modules

  tasks:

    - name: Randomize ARO resource names
      set_fact:
         aro_cluster_name: "aro{{ resource_group | hash('md5') | truncate(10, True, '') }}"

    - name: Create Azure Red Hat OpenShift Cluster
      openshiftmanagedcluster:
        resource_group: "{{ resource_group }}"
        name: "{{ aro_cluster_name }}"
        location: eastus
        open_shift_version: v3.11
        network_profile:
          vnet_cidr: 10.0.0.0/8
        router_profiles:
          - name: default
        master_pool_profile:
          name: master
          count: 3
          vm_size: Standard_D4s_v3
          subnet_cidr: 10.0.0.0/24
          os_type: Linux
        agent_pool_profiles:
          - name: infra
            count: 2
            vm_size: Standard_D4s_v3
            subnet_cidr: 10.0.0.0/24
            os_type: Linux
            role: infra
          - name: compute
            count: 4
            vm_size: Standard_D4s_v3
            subnet_cidr: 10.0.0.0/24
            os_type: Linux
            role: compute
        auth_profile:
          identity_providers:
            - name: Azure AD
              provider:
                kind: AADIdentityProvider
                clientId: "{{ aro_client_id }}"
                secret: "{{ aro_secret }}"
                tenantId: "{{ aro_tenant_id }}"
      register: output

    - debug:
        msg: "Your public hostname is:  https://{{ output.properties.publicHostname }}"

    - debug:
        msg: "The REPLY_URI to add to AAD is:  https://{{ output.properties.publicHostname }}/oauth2callback/Azure%20AD"

