- hosts: localhost
  vars_files:
    - ./vars-myvars.yml
  roles:
    - ./modules
  tasks:

    - name: Randomize ARO resource names
      set_fact:
         aro_cluster_name: "aro-{{ resource_group | hash('md5') | truncate(10, True, '') }}"

    - name: Get cluster information
      openshiftmanagedcluster_info:
        resource_group: "{{ aro_cluster_name }}"
        name: "{{ aro_cluster_name }}"
      register: output

    - name: Deploy an image to ARO
      k8s_raw:
          state: present
          force: true
          src: "deployment-aro.yml"
          host: "https://{{ output.open_shift_managed_clusters.properties.publicHostname }}"
          api_key: "{{ aro_key }}"
      register: output2

    - name: Expose to external
      k8s_raw:
          state: present
          src: "service-aro.yml"
          host: "https://{{ output.open_shift_managed_clusters.properties.publicHostname }}"
          api_key: "{{ aro_key }}"
      register: output3

    - debug:
        msg: "The ARO application is being created.  Keep an eye on the output of 'oc get svc' until you notice an IP address has been assigned to the load balancer. When it has, attempt to connect to it."


