- hosts: localhost
  vars_files:
    - ./vars-myvars.yml
  roles:
    - ./modules
  tasks:

    - name: Get cluster information
      openshiftmanagedcluster_info:
        resource_group: "aroaafe82b56d"
        name: "aroaafe82b56d"
      register: output

    - debug:
        var: output

    - name: Deploy an image to ARO
      k8s_raw:
          state: present
          force: true
          src: "deployment-aro.yml"
          host: "https://{{ output.open_shift_managed_clusters.properties.publicHostname }}"
          api_key: "{{ aro_key }}"
      register: output2

    - debug:
        var: output2

    - name: Expose to external
      k8s_raw:
          state: present
          src: "service-aro.yml"
          host: "https://{{ output.open_shift_managed_clusters.properties.publicHostname }}"
          api_key: "{{ aro_key }}"
      register: output3

    - debug:
        var: output3

    - debug:
          msg: "http://{{ output.result.status.loadBalancer.ingress[0].ip }}"

