---
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - ./modules 
  tasks:
    - name: Deploy an image to ARO
      k8s_raw:
          state: present
          force: true
          src: "deployment-aro.yml"
          host: https://openshift.46a0e43a9e5b4b80a523.eastus.azmosa.io
          api_key: "{{ aro_key }}"

    - name: Expose to external
      k8s_raw:
          state: present
          src: "service-aro.yml"
          host: https://openshift.46a0e43a9e5b4b80a523.eastus.azmosa.io
          api_key: "{{ aro_key }}"
      register: output

    - debug:
          msg: "http://{{ output.result.status.loadBalancer.ingress[0].ip }}"
