---
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - ./modules 
  tasks:
    - name: Log in (obtain access token)
      k8s_auth:
        username: "{{ client_id }}"
        password: "{{ secret }}"
        host: https://openshift.xxxxxxxxxxxxxxxxxxx.eastus.azmosa.io
      register: k8s_auth_results

    - name: Deploy Application
      k8s:
        state: present
        definition: "{{ lookup('file', './deployment.yml') }}"
