---
- hosts: localhost
  vars_files:
    - vars.yml
  roles:
    - ./modules 
  tasks:
    - name: Create/Update OpenShift Managed Cluster
      azure_rm_resource:
        url: /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourcegroups/{{ resource_group }}/providers/Microsoft.ContainerService/openshiftmanagedClusters/myOpenShiftManagedClusterNew
        method: GET
      register: output

    - debug:
        var: output
